const assert=require('node:assert/strict'),fs=require('node:fs');
const {group,identity,expandDefaults}=require('../source-registry.js');
const load=name=>JSON.parse(fs.readFileSync('config/'+name+'.json','utf8'));
const old=[...load('sources'),...load('research-sources')];
const expanded=expandDefaults(load('expanded-sources'));
const entries=group([...old,...expanded]);
const beta=entries.filter(s=>s.key==='socialbeta.com');
assert.equal(beta.length,1);assert.equal(beta[0].name,'SocialBeta');assert.equal(beta[0].members.length,6);
assert.equal(identity({base_url:'https://m.pchouse.com.cn/article/1.html'}).key,'pchouse.com.cn');
assert.equal(identity({base_url:'https://www.kukahome.com.hk/'}).key,'kukahome.com.hk');
assert.notEqual(identity({base_url:'https://weibo.com/gujiajiaju'}).key,identity({base_url:'https://weibo.com/linshimuye'}).key);
assert.equal(identity({base_url:'javascript:alert(1)'}),null);
assert.ok(expanded.every(s=>s.enabled&&s.pools.includes('research')&&s.pools.includes('competitor')));
assert.equal(entries.length-group(old).length,18);
assert.ok(entries.some(s=>s.name==='床墊大叔'));assert.ok(entries.some(s=>s.name==='老爸评测·B站'));
console.log(JSON.stringify({passed:true,previousUnique:group(old).length,totalUnique:entries.length,newUnique:18,autoConfigured:expanded.filter(s=>s.mode==='html').length}));
