const assert=require('node:assert/strict'),fs=require('node:fs');
const {group,identity,expandDefaults}=require('../source-registry.js');
const load=name=>JSON.parse(fs.readFileSync('config/'+name+'.json','utf8'));
const old=[...load('sources'),...load('research-sources')];
const expanded=expandDefaults(load('expanded-sources'));
const creators=expandDefaults(load('creator-sources'));
const entries=group([...old,...expanded,...creators]);
const beta=entries.filter(s=>s.key==='socialbeta.com');
assert.equal(beta.length,1);assert.equal(beta[0].name,'SocialBeta');assert.equal(beta[0].members.length,6);
assert.equal(identity({base_url:'https://m.pchouse.com.cn/article/1.html'}).key,'pchouse.com.cn');
assert.equal(identity({base_url:'https://www.kukahome.com.hk/'}).key,'kukahome.com.hk');
assert.notEqual(identity({base_url:'https://weibo.com/gujiajiaju'}).key,identity({base_url:'https://weibo.com/linshimuye'}).key);
assert.equal(identity({base_url:'javascript:alert(1)'}),null);
assert.ok(expanded.every(s=>s.enabled&&s.pools.includes('research')&&s.pools.includes('competitor')));
assert.equal(entries.length-group(old).length,116);
const {category}=require('../source-registry.js');
assert.equal(entries.filter(s=>category(s)==='creators').length,100);
assert.equal(entries.filter(s=>category(s)==='accounts').length,3);
assert.equal(category(entries.find(s=>s.name==='老爸评测·B站')),'creators');
assert.equal(category(entries.find(s=>s.name==='慕思官方资讯')),'reference');
assert.equal(category(entries.find(s=>s.name==='SocialBeta')),'websites');
assert.ok(entries.filter(s=>category(s)==='websites').every(s=>!/品牌官网|品牌官方|协会|展会|会议/.test(s.platform)));
assert.equal(new Set(creators.map(s=>s.creator_id)).size,98);
assert.equal(new Set(creators.map(s=>s.base_url)).size,98);
assert.ok(creators.every(s=>s.mode==='manual'&&s.evidence_url&&identity({base_url:s.evidence_url})&&s.verified_at&&s.verification_scope));
assert.equal(group([{...creators[0],base_url:'https://www.bilibili.com/video/BV1AAA/'},{...creators[0],base_url:'https://www.bilibili.com/video/BV1BBB/'}]).length,1);
assert.equal(identity({...creators[0],base_url:'javascript:alert(1)'}),null);
assert.ok(entries.some(s=>s.name==='床墊大叔'));assert.ok(entries.some(s=>s.name==='老爸评测·B站'));
console.log(JSON.stringify({passed:true,totalUnique:entries.length,creators:100,newCreators:98,brandAccounts:3,autoConfigured:expanded.filter(s=>s.mode==='html').length}));
